#!/usr/bin/env bash
# No roadmap header on purpose -- this is a defect/feature spec for TODO id:e8af, which has
# no ROADMAP twin (it was filed directly into TODO.md). Failures always count.
#
# id:e8af -- a DERIVED meeting-backlink index answering "which meetings already discussed
# this id?", the "haven't we settled this before" failure. Measured on the live tree
# 2026-09-01: 667 distinct ids cited across 218 notes, 261 of them in two or more notes.
# (The TODO line quotes 659/217/259, taken a few notes earlier; the citation SET was
# cross-checked against an independent naive scan and matched exactly.)
#
# The index is its OWN derived file (docs/ledger-notes/BACKLINKS.md), never an embedded
# section inside a hand-edited file: markdown stays SSOT, the index is a cache (id:2840).
#
# Contract asserted here:
#   A. --write is IDEMPOTENT -- running it twice yields a byte-identical file.
#   B. an id cited in >=2 notes lists ALL of them; an id cited in NO note never appears.
#   C. --check exits 0 when the index is current, non-zero once it is stale.
#   D. the tool NEVER clobbers hand-edited content -- an existing target WITHOUT the
#      generated-by marker is REFUSED (non-zero) and left byte-for-byte untouched,
#      in --write and in --check alike.
#
# fails-against: the feature and this spec land in the SAME commit, so there is no ancestor
# tree to check out; the negative case is "the tool does not exist yet", which every
# assertion below fails against.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOL="$ROOT/tools/meeting-backlinks.py"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

notes="$tmp/meeting-notes"
idx_dir="$tmp/ledger-notes"
idx="$idx_dir/BACKLINKS.md"
mkdir -p "$notes" "$idx_dir"

fail=0
report() { echo "FAIL: $1"; fail=1; }

if [[ ! -x "$TOOL" ]]; then
  report "tools/meeting-backlinks.py must exist and be executable"
  echo "PARTIAL: tool missing, remaining assertions cannot run"
  exit 1
fi

# Fixture notes.
#   aa11 -- cited in TWO notes, once as an HTML-comment id and once as bare prose.
#   aa22 -- cited in ONE note only.
#   dddd -- cited NOWHERE (must never appear in the index).
cat > "$notes/2026-01-01-0900-first.md" <<'EOF'
# First meeting

- [ ] decide the thing <!-- id:aa11 -->
- [ ] a second thing <!-- id:aa22 -->
EOF

cat > "$notes/2026-02-02-1000-second.md" <<'EOF'
# Second meeting

We already settled id:aa11 in the first meeting; this note only revisits the framing.
A near-miss token like invalid:aa33 or roadmap:aa44 is NOT an id citation.
EOF

run() { python3 "$TOOL" --notes-dir "$notes" --index "$idx" "$@"; }

# --- A. idempotent regeneration -------------------------------------------------------
if ! run --write >/dev/null 2>&1; then
  report "A: --write must succeed on a fresh index path"
fi
cp -- "$idx" "$tmp/first.md"
if ! run --write >/dev/null 2>&1; then
  report "A: a second --write must succeed"
fi
cmp -s "$tmp/first.md" "$idx" \
  || report "A: --write must be IDEMPOTENT (two runs must be byte-identical)"

# --- B. backlink content --------------------------------------------------------------
body="$(cat "$idx")"

grep -q 'id:aa11' <<<"$body" \
  || report "B: an id cited in two notes must appear in the index"
line_aa11="$(grep -F -m1 'aa11' <<<"$body")"
grep -q '2026-01-01-0900-first' <<<"$line_aa11" \
  || report "B: id aa11's entry must list the note that cites it via an HTML-comment id"
grep -q '2026-02-02-1000-second' <<<"$line_aa11" \
  || report "B: id aa11's entry must list the note that cites it in BARE PROSE (a passing prose mention IS a prior discussion)"

line_aa22="$(grep -F -m1 'aa22' <<<"$body" || true)"
[[ -n "$line_aa22" ]] \
  || report "B: an id cited in exactly one note must still appear"
grep -q '2026-02-02-1000-second' <<<"${line_aa22:-}" \
  && report "B: id aa22 must NOT be attributed to a note that never cites it"

grep -q 'dddd' <<<"$body" \
  && report "B: an id cited in NO note must not appear in the index"

grep -qE 'aa33|aa44' <<<"$body" \
  && report "B: near-miss tokens (invalid:aa33 / roadmap:aa44) must NOT be read as id citations"

grep -q 'GENERATED by tools/meeting-backlinks.py' <<<"$body" \
  || report "B: the index must carry a generated-by header marker"

# --- C. --check drift -----------------------------------------------------------------
if ! run --check >/dev/null 2>&1; then
  report "C: --check must exit 0 when the index is current"
fi
cat > "$notes/2026-03-03-1100-third.md" <<'EOF'
# Third meeting

Revisiting id:aa11 yet again, plus a fresh id:aa55.
EOF
if run --check >/dev/null 2>&1; then
  report "C: --check must exit non-zero when the index is STALE"
fi
run --write >/dev/null 2>&1 || true
if ! run --check >/dev/null 2>&1; then
  report "C: --check must return to exit 0 after a regeneration"
fi

# --- D. never clobber hand-edited content ---------------------------------------------
foreign="$tmp/foreign.md"
cat > "$foreign" <<'EOF'
# Hand-written notes about backlinks

This file was written by a human and carries no generated-by marker.
EOF
cp -- "$foreign" "$idx"

if run --write >/dev/null 2>&1; then
  report "D: --write must REFUSE a target that lacks the generated-by marker"
fi
cmp -s "$foreign" "$idx" \
  || report "D: a refused --write must leave the hand-edited target byte-for-byte untouched"

if run --check >/dev/null 2>&1; then
  report "D: --check must also refuse (non-zero) on a target lacking the marker"
fi
cmp -s "$foreign" "$idx" \
  || report "D: --check must never modify the target"

if (( fail )); then
  echo "--- index on disk ---"
  head -40 -- "$idx" 2>/dev/null || true
  exit 1
fi
echo "PASS: meeting-backlinks.py builds an idempotent, drift-checked, clobber-safe backlink index (id:e8af)"
