#!/usr/bin/env bash
# Specs TODO id:e647 — the reviewer-at-integrate version bumper (`relay/scripts/version-bump.sh`).
# (No `# roadmap:XXXX` header: e647 is a TODO/design id, not a ROADMAP queue item; this is a
#  /meeting Class-1 inline impl, so the test must end GREEN — it is NOT expected-red, mirroring
#  tests/test_changelog_derive.sh.)
#
# Design (meeting docs/meeting-notes/2026-07-17-1541-semver-trigger-and-fleet-changelog.md):
#   D1 — the reviewer bumps at integrate, once per USER-OBSERVABLE close. The level (minor/patch)
#        is the reviewer's judgement (an INPUT — "user-observable" is not derivable), NOT computed.
#   loose-0.x — patch=z+1; minor=y+1,z=0; MAJOR never changes here.
#   bump-includes-lockfile — regen the lockfile + git add it in the SAME bump commit; leave the
#        tree CLEAN (a dirty tree trips clean-tree-gate.sh and defers the repo).
#   finding (b) — the reader MUST be `git describe --tags --match 'v[0-9]*'` (WITH --tags), because
#        some repos create LIGHTWEIGHT v* tags that plain `git describe` silently ignores.
#   finding (c) — the zkm parent bump CASCADES to plugin uv.locks via the repo's OWN
#        scripts/relock-plugins.sh; call that tool, never re-implement the cascade.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VB="$ROOT/relay/scripts/version-bump.sh"
pass() { echo "PASS: $*"; }
fail() { echo "FAIL: $*"; exit 1; }

[[ -x "$VB" ]] || fail "version-bump.sh not found/executable at $VB"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

mkrepo() { # mkrepo <name> -> path (an initialised git repo, one commit, no manifest yet)
  local r="$TMP/$1"
  mkdir -p "$r"
  git -C "$r" init -q
  git -C "$r" config user.email t@e.st
  git -C "$r" config user.name t
  git -C "$r" config commit.gpgsign false
  git -C "$r" config tag.gpgsign false
  echo x > "$r/f"; git -C "$r" add -A; git -C "$r" commit -qm init
  printf '%s' "$r"
}
clean() { # clean <repo> — assert the working tree carries NO changes (bump-includes-lockfile)
  [[ -z "$(git -C "$1" status --porcelain)" ]] || {
    echo "  dirty tree:"; git -C "$1" status --porcelain | sed 's/^/    /'
    fail "$2"
  }
}

# A hermetic lockfile-regen stub: `uv lock`/`npm install` need network+deps, so the real command
# is injected via VERSION_BUMP_LOCK_CMD. The stub just writes the lockfile so we can prove it is
# regenerated + staged + committed in the SAME bump commit.
LOCK_STUB_PY='printf "lock @ %s\n" "$(cat pyproject.toml 2>/dev/null || cat package.json)" > uv.lock'
LOCK_STUB_JS='printf "lock\n" > package-lock.json'

# ── (1) NO MANIFEST → logged NO-OP, exit 0, nothing changed (the version-less exemption). ──
R1="$(mkrepo nomanifest)"
before="$(git -C "$R1" rev-parse HEAD)"
"$VB" "$R1" --level minor >/dev/null 2>&1 \
  || fail "(1) version-bump must exit 0 (no-op) when no manifest is present, not error"
[[ "$(git -C "$R1" rev-parse HEAD)" == "$before" ]] \
  || fail "(1) version-bump created a commit in a manifest-less repo — must be a pure no-op"
[[ -z "$(git -C "$R1" tag -l)" ]] \
  || fail "(1) version-bump created a tag in a manifest-less repo — must be a pure no-op"
clean "$R1" "(1) manifest-less repo left dirty by a no-op"
pass "(1) no manifest -> no-op, exit 0, no commit, no tag (version-less exemption)"

# ── (2) pyproject MINOR: 0.4.0 -> 0.5.0; manifest line updated; lockfile regen+staged; clean; tag. ──
R2="$(mkrepo pyminor)"
printf '[project]\nname = "x"\nversion = "0.4.0"\n' > "$R2/pyproject.toml"
git -C "$R2" add -A; git -C "$R2" commit -qm manifest
out="$(VERSION_BUMP_LOCK_CMD="$LOCK_STUB_PY" "$VB" "$R2" --level minor)" \
  || fail "(2) pyproject minor bump failed"
[[ "$out" == "v0.5.0" ]] || fail "(2) expected stdout 'v0.5.0', got '$out'"
grep -qxF 'version = "0.5.0"' "$R2/pyproject.toml" \
  || fail "(2) pyproject version line not rewritten to 0.5.0"
grep -qxF 'version = "0.4.0"' "$R2/pyproject.toml" \
  && fail "(2) old version line still present after bump"
[[ -f "$R2/uv.lock" ]] || fail "(2) lockfile not regenerated by the injected VERSION_BUMP_LOCK_CMD"
git -C "$R2" cat-file -e HEAD:uv.lock 2>/dev/null \
  || fail "(2) uv.lock not committed in the bump commit (bump-includes-lockfile)"
clean "$R2" "(2) tree left dirty after bump — would trip clean-tree-gate.sh"
git -C "$R2" cat-file -e HEAD:pyproject.toml
[[ "$(git -C "$R2" cat-file -t v0.5.0 2>/dev/null)" == "tag" ]] \
  || fail "(2) v0.5.0 is not an ANNOTATED tag (finding b: lightweight tags are silently skipped)"
pass "(2) pyproject minor: 0.4.0->0.5.0, manifest+lockfile committed clean, annotated tag"

# ── (3) pyproject PATCH: 0.4.0 -> 0.4.1. ──
R3="$(mkrepo pypatch)"
printf '[project]\nversion = "0.4.0"\n' > "$R3/pyproject.toml"
git -C "$R3" add -A; git -C "$R3" commit -qm manifest
out="$(VERSION_BUMP_LOCK_CMD="$LOCK_STUB_PY" "$VB" "$R3" --level patch)" \
  || fail "(3) pyproject patch bump failed"
[[ "$out" == "v0.4.1" ]] || fail "(3) expected 'v0.4.1', got '$out'"
grep -qxF 'version = "0.4.1"' "$R3/pyproject.toml" || fail "(3) manifest not 0.4.1"
clean "$R3" "(3) tree dirty after patch bump"
pass "(3) pyproject patch: 0.4.0 -> 0.4.1"

# ── (4) loose-0.x: minor ZEROES the patch; MAJOR never changes. ──
R4="$(mkrepo loose)"
printf '[project]\nversion = "1.4.7"\n' > "$R4/pyproject.toml"
git -C "$R4" add -A; git -C "$R4" commit -qm manifest
out="$(VERSION_BUMP_LOCK_CMD="$LOCK_STUB_PY" "$VB" "$R4" --level minor)" \
  || fail "(4) minor bump failed"
[[ "$out" == "v1.5.0" ]] || fail "(4) minor of 1.4.7 must be 1.5.0 (y+1, z=0, major untouched), got '$out'"
grep -qxF 'version = "1.5.0"' "$R4/pyproject.toml" || fail "(4) manifest not 1.5.0"
pass "(4) loose-0.x: minor zeroes patch, major unchanged (1.4.7 -> 1.5.0)"

# ── (5) READER (finding b): `git describe --tags --match 'v[0-9]*'` finds a LIGHTWEIGHT v* tag
#        that plain `git describe --match` (no --tags) silently ignores. ──
R5="$(mkrepo reader)"
printf '[project]\nversion = "0.20.0"\n' > "$R5/pyproject.toml"
git -C "$R5" add -A; git -C "$R5" commit -qm manifest
git -C "$R5" tag v0.21.0                       # LIGHTWEIGHT tag (no -a) — the zkm autotag shape
desc_with="$(git -C "$R5" describe --tags --match 'v[0-9]*' 2>/dev/null || true)"
[[ "$desc_with" == v0.21.0* ]] \
  || fail "(5) reader with --tags did not find the lightweight v0.21.0 (got '$desc_with')"
desc_without="$(git -C "$R5" describe --match 'v[0-9]*' 2>/dev/null || true)"
[[ "$desc_without" == v0.21.0* ]] \
  && fail "(5) plain describe (no --tags) unexpectedly found the lightweight tag — test premise void"
pass "(5) reader: --tags finds lightweight v* tags; plain describe misses them (finding b)"

# ── (6) package.json smoke: 0.4.0 -> 0.5.0 (minor). ──
R6="$(mkrepo pkgjson)"
printf '{\n  "name": "x",\n  "version": "0.4.0"\n}\n' > "$R6/package.json"
git -C "$R6" add -A; git -C "$R6" commit -qm manifest
out="$(VERSION_BUMP_LOCK_CMD="$LOCK_STUB_JS" "$VB" "$R6" --level minor)" \
  || fail "(6) package.json minor bump failed"
[[ "$out" == "v0.5.0" ]] || fail "(6) expected 'v0.5.0', got '$out'"
grep -qF '"version": "0.5.0"' "$R6/package.json" || fail "(6) package.json version not 0.5.0"
[[ -f "$R6/package-lock.json" ]] || fail "(6) package-lock.json not regenerated"
git -C "$R6" cat-file -e HEAD:package-lock.json 2>/dev/null \
  || fail "(6) package-lock.json not committed in the bump commit"
clean "$R6" "(6) tree dirty after package.json bump"
pass "(6) package.json smoke: 0.4.0 -> 0.5.0, lockfile committed clean"

# ── (7) CASCADE gate (finding c): if scripts/relock-plugins.sh exists, it is INVOKED (not
#        re-implemented). A stub proves the gate fires; a repo without it is untouched. ──
R7="$(mkrepo cascade)"
printf '[project]\nversion = "0.4.0"\n' > "$R7/pyproject.toml"
mkdir -p "$R7/scripts"
cat > "$R7/scripts/relock-plugins.sh" <<'SH'
#!/usr/bin/env bash
echo "cascade-ran $*" > "$(git rev-parse --show-toplevel)/.cascade-marker"
SH
chmod +x "$R7/scripts/relock-plugins.sh"
git -C "$R7" add -A; git -C "$R7" commit -qm manifest
VERSION_BUMP_LOCK_CMD="$LOCK_STUB_PY" "$VB" "$R7" --level patch >/dev/null \
  || fail "(7) bump with a cascade script present failed"
[[ -f "$R7/.cascade-marker" ]] \
  || fail "(7) scripts/relock-plugins.sh was not invoked (cascade gate did not fire)"
pass "(7) cascade gate: scripts/relock-plugins.sh invoked when present (finding c)"

# ── (8) INTEGRATOR wiring: relay-loop.js must invoke version-bump.sh AND still pass --version to
#        changelog-append.sh (bump BEFORE changelog so the release bucket gets the version). ──
#        id:087b RELOCATION — the integrator is now relay/scripts/integrate.sh, dispatched by
#        relay-loop.js as one mechanical hop, so the wiring lives there. The ORDER invariant
#        (bump BEFORE changelog) is now checkable as real code order rather than prompt order.
JS="$ROOT/relay/scripts/relay-loop.js"
INTEG="$ROOT/relay/scripts/integrate.sh"
[[ -x "$INTEG" ]] || fail "(8) integrate.sh not found/executable at $INTEG"
grep -q 'relay/scripts/integrate.sh' "$JS" \
  || fail "(8) relay-loop.js does not dispatch integrate.sh — the bump is wired to nothing"
grep -q 'version-bump.sh' "$INTEG" \
  || fail "(8) integrate.sh never invokes version-bump.sh (e647 not wired)"
grep -q 'changelog-append.sh' "$INTEG" \
  || fail "(8) integrate.sh no longer invokes changelog-append.sh (b8fa wiring lost)"
grep -qF -- 'cl_args+=(--version "$bump_version")' "$INTEG" \
  || fail "(8) integrate.sh does not pass --version to changelog-append.sh (release bucketing lost)"
vb_line=$(grep -n '"\$VERSION_BUMP"' "$INTEG" | head -1 | cut -d: -f1)
cl_line=$(grep -n '"\$CHANGELOG"' "$INTEG" | head -1 | cut -d: -f1)
[[ -n "$vb_line" && -n "$cl_line" ]] || fail "(8) could not locate both the bump and changelog calls in integrate.sh"
[[ "$vb_line" -lt "$cl_line" ]] \
  || fail "(8) version-bump runs AFTER changelog-append (bump=$vb_line, changelog=$cl_line) — the release bucket would miss the new version"
pass "(8) integrator wiring: version-bump.sh invoked before changelog-append.sh; --version passed through"

# ── (8b) id:087b — the bump TRIGGER is never guessed. It resolves from explicit input, a
#        version-less repo, a non-substantive close, or a durable relay.toml bump_policy; the
#        undeterminable case is a LOUD HANDBACK[bump], never a silent bump or a silent skip. ──
grep -q 'HANDBACK\|handback bump' "$INTEG" || fail "(8b) integrate.sh has no handback mechanism"
grep -q 'handback bump "\$EX_BUMP"' "$INTEG" \
  || fail "(8b) integrate.sh does not hand back loudly when the semver bump trigger is unresolvable (id:e647 — it must never silently bump or silently skip)"
grep -q 'EX_BUMP=' "$INTEG" \
  || fail "(8b) the bump handback has no distinct exit code"
# The trigger must be resolved BEFORE the merge, so an unresolvable trigger leaves main unmoved.
bump_res_line=$(grep -n 'handback bump "\$EX_BUMP"' "$INTEG" | head -1 | cut -d: -f1)
merge_line=$(grep -n 'merge --no-ff "\$branch"' "$INTEG" | head -1 | cut -d: -f1)
[[ -n "$bump_res_line" && -n "$merge_line" ]] || fail "(8b) could not locate both the bump handback and the merge"
[[ "$bump_res_line" -lt "$merge_line" ]] \
  || fail "(8b) the bump trigger is resolved AFTER the merge (bump=$bump_res_line, merge=$merge_line) — a HANDBACK[bump] would strand a half-integrated repo"
pass "(8b) the semver bump trigger is resolved pre-merge and hands back loudly when undeterminable (id:e647)"

# ── (9) relay-loop.js still parses + template lint passes after the integrator edit. ──
node --check "$JS" >/dev/null 2>&1 || fail "(9) relay-loop.js fails node --check after wiring edit"
if [[ -f "$ROOT/relay/scripts/lint-workflow-templates.mjs" ]]; then
  node "$ROOT/relay/scripts/lint-workflow-templates.mjs" "$JS" >/dev/null 2>&1 \
    || fail "(9) lint-workflow-templates.mjs failed on relay-loop.js after wiring edit"
fi
pass "(9) relay-loop.js still parses (node --check + template lint) after the integrator edit"

echo "ALL PASS: id:e647 version-bump.sh reviewer-at-integrate bumper + integrator wiring"
