#!/usr/bin/env bash
# id:dd59 — ledger-slice.sh must also slice a SET of ids in one call, for the REVIEW case
# (many units in one round) rather than only the single-executor-unit case id:e68f already
# covers. The relay-loop.js half that derives the id set and calls this script is a SEPARATE,
# owner-authored change (do not conflate) — this test only exercises the slicer.
#
# (No `# roadmap:` header: id:dd59 is a TODO.md-only item, not a ROADMAP.md unit, so its
# failures always count — never EXPECTED-RED.)
#
# Hermetic: mktemp -d fixture repo, bash + coreutils only, no network, never touches ~/.claude.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SLICE="$ROOT/relay/scripts/ledger-slice.sh"

pass=0; fail=0
ok()  { echo "ok: $*"; pass=$((pass+1)); }
bad() { echo "BAD: $*"; fail=$((fail+1)); }

[[ -x "$SLICE" ]] || { echo "FAIL: $SLICE missing/not executable"; exit 1; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
R="$TMP/repo"; mkdir -p "$R"

{
  printf '# ROADMAP\n\n## Items\n\n'
  printf -- '<!-- gated-on:2222 -->\n'
  printf -- '- [ ] [ROUTINE] **ITEM ONE** — build the widget <!-- id:1111 -->\n'
  printf -- '  - **Acceptance**: the widget exists.\n\n'
  printf -- '- [ ] [INPUT - decision] **GATE TARGET** — owner must pick a widget shape <!-- id:2222 -->\n\n'
  printf -- '- [ ] [ROUTINE] **ITEM THREE** — an unrelated unit <!-- id:3333 -->\n\n'
  printf -- '- [ ] [ROUTINE] **ITEM FOUR** — never requested <!-- id:4444 -->\n\n'
} > "$R/ROADMAP.md"

{
  printf '# TODO\n\n## Current\n\n'
  printf -- '- [ ] twin of item one <!-- id:1111 -->\n'
  printf -- '- [ ] twin of item three <!-- id:3333 -->\n'
} > "$R/TODO.md"

# ── (1) REGRESSION PIN: --id single-id output is BYTE-IDENTICAL to before this change. ──────
O_single="$TMP/single.md"
"$SLICE" --repo repo --path "$R" --id 1111 --out "$O_single" >/dev/null

read -r -d '' EXPECTED_SINGLE <<'EOF' || true
# Ledger slice — repo id:1111

## Repo state
- repo: repo
- path: __PATH__
- dispatched item: id:1111 (ROADMAP.md:6)
- owning section: ## Items
- ROADMAP.md: __RM_BYTES__ B; TODO.md: __TODO_BYTES__ B
- generated by relay/scripts/ledger-slice.sh (id:e68f)

> This slice is the DEFAULT context for this unit, not a boundary (id:9663): the
> ledgers remain readable at their canonical paths. Read them only if this slice is
> genuinely insufficient, and say so in your handback if it was.

## Dispatched item (ROADMAP.md)

<!-- gated-on:2222 -->
- [ ] [ROUTINE] **ITEM ONE** — build the widget <!-- id:1111 -->
  - **Acceptance**: the widget exists.

## Typed edges

- id:2222 — ROADMAP.md:9
  - [ ] [INPUT - decision] **GATE TARGET** — owner must pick a widget shape <!-- id:2222 -->

## TODO.md twin (design ledger, same id)

- [ ] twin of item one <!-- id:1111 -->
EOF

rm_bytes=$(wc -c < "$R/ROADMAP.md")
todo_bytes=$(wc -c < "$R/TODO.md")
EXPECTED_SINGLE="${EXPECTED_SINGLE//__PATH__/$R}"
EXPECTED_SINGLE="${EXPECTED_SINGLE//__RM_BYTES__/$rm_bytes}"
EXPECTED_SINGLE="${EXPECTED_SINGLE//__TODO_BYTES__/$todo_bytes}"

if diff <(printf '%s\n' "$EXPECTED_SINGLE") "$O_single" >"$TMP/diff.txt"; then
  ok "id:dd59: --id single-id output is byte-identical to the pre-existing e68f/b015 format"
else
  bad "id:dd59: --id single-id output CHANGED — the multi-id addition must not touch this path. diff:"
  cat "$TMP/diff.txt"
fi

# ── (2) --ids with TWO ids unions both items' blocks. ───────────────────────────────────────
O_multi="$TMP/multi.md"
"$SLICE" --repo repo --path "$R" --ids 1111,3333 --out "$O_multi" >/dev/null
grep -q 'ITEM ONE' "$O_multi" && ok "multi-id slice contains item one" || bad "id:dd59: multi-id slice drops item one"
grep -q 'ITEM THREE' "$O_multi" && ok "multi-id slice contains item three" || bad "id:dd59: multi-id slice drops item three"
grep -q 'id:2222' "$O_multi" && ok "multi-id slice resolves item one's gated-on: edge" || bad "id:dd59: multi-id slice drops the gate edge"
grep -q 'twin of item one' "$O_multi" && ok "multi-id slice carries item one's TODO twin" || bad "id:dd59: multi-id slice drops item one's TODO twin"
grep -q 'twin of item three' "$O_multi" && ok "multi-id slice carries item three's TODO twin" || bad "id:dd59: multi-id slice drops item three's TODO twin"
grep -q 'ITEM FOUR' "$O_multi" && bad "id:dd59: multi-id slice leaked an item (id:4444) nobody requested" || ok "multi-id slice excludes an unrequested item"

# ── (3) Overlapping/duplicate ids do not double-emit. ───────────────────────────────────────
O_dup="$TMP/dup.md"
"$SLICE" --repo repo --path "$R" --ids 1111,1111,3333 --out "$O_dup" >/dev/null
n=$(grep -c 'ITEM ONE' "$O_dup" || true)
[[ "$n" -eq 1 ]] && ok "duplicate id in --ids is de-duped (ITEM ONE emitted once)" || bad "id:dd59: duplicate id in --ids emitted ITEM ONE $n times, expected 1"

# A requested id whose block itself CONTAINS a gated-on: edge to ANOTHER requested id must
# still list that edge only once overall (the edge resolution and the dispatched-item section
# for id:2222-if-requested must not both appear duplicated).
O_overlap="$TMP/overlap.md"
"$SLICE" --repo repo --path "$R" --ids 1111,2222 --out "$O_overlap" >/dev/null
n2=$(grep -c '^- id:2222 —' "$O_overlap" || true)
[[ "$n2" -eq 0 ]] && ok "an edge target that is ALSO a requested id is not re-listed under Typed edges (already has its own Dispatched-item section)" || bad "id:dd59: id:2222 listed under Typed edges even though it is co-dispatched ($n2 times)"
n3=$(grep -c 'GATE TARGET' "$O_overlap" || true)
[[ "$n3" -eq 1 ]] && ok "the co-dispatched gate target's block is emitted exactly once" || bad "id:dd59: co-dispatched gate target block emitted $n3 times, expected 1"

# ── (4) An unresolvable id is reported LOUDLY (stderr) but does NOT fail the run. ───────────
# CONTRACT CHANGED 2026-09-01 on live evidence (run relay-20260901-100342-3206), inverting
# what this block used to assert. It required a NON-ZERO exit on partial resolution. The
# mechanical hop flattens ANY non-zero exit to `MECH-ERROR exit=N`, and relay-loop.js's
# `if (/^MECH-ERROR exit=/) return null` then DISCARDED a perfectly good slice and fell back
# to the unsliced brief — the prompt-size gate refused the dispatch at ~473,290 tok. Partial
# resolution is the NORMAL case (of 14 ids derived live, 4313 was closed-and-archived and
# 3e13 was an inbox routing token), so a non-zero exit there made the feature never fire.
# Non-zero now means exactly one thing: no usable slice path on stdout. The LOUD naming of
# unresolved ids (id:4347) is the guarantee that survives, and is still asserted below.
#        ids that DID resolve still get a slice (reported-and-continue, id:4347).
O_partial="$TMP/partial.md"
err="$TMP/err.txt"
rc=0
"$SLICE" --repo repo --path "$R" --ids 1111,ffff --out "$O_partial" >/dev/null 2>"$err" || rc=$?
[[ "$rc" -eq 0 ]] && ok "one unresolvable id among several still exits 0 (a written slice is a success)" || bad "id:dd59: partial resolution exited $rc — a non-zero exit here is flattened to MECH-ERROR and the good slice is discarded"
grep -q 'ffff' "$err" && ok "the unresolvable id is NAMED on stderr, not silently skipped (id:4347)" || bad "id:dd59: unresolvable id ffff never named on stderr"
if [[ -s "$O_partial" ]]; then
  grep -q 'ITEM ONE' "$O_partial" && ok "the id that DID resolve still gets a slice (reported-and-continue, not whole-batch-fatal)" || bad "id:dd59: resolvable id's block missing from the partial slice"
else
  bad "id:dd59: no slice written at all when one of two ids was unresolvable — should still slice the resolvable one"
fi

# If NONE of the requested ids resolve, no file is written (matches the single-id refusal).
O_none="$TMP/none.md"
rc2=0
"$SLICE" --repo repo --path "$R" --ids ffff,eeee --out "$O_none" >/dev/null 2>"$TMP/err2.txt" || rc2=$?
[[ "$rc2" -ne 0 ]] && ok "all-unresolvable --ids set exits non-zero ($rc2)" || bad "id:dd59: all-unresolvable set exited 0"
[[ ! -s "$O_none" ]] && ok "all-unresolvable --ids set writes no slice file (mirrors the single-id refusal)" || bad "id:dd59: a slice file was written even though nothing resolved"

# ── (4b) TODO-ONLY ids are SLICED, not dropped (id:dd59 coverage gap fix). ──────────────────
# ROADMAP.md is the relay's execution queue, but many ids live only in TODO.md (the design
# ledger) and are worked there. Measured live before this fix: of 6 ids derived from one real
# checkpoint range, FOUR owned no ROADMAP line and vanished from the slice, so a reviewer saw
# 2 of 6 worked items with no signal the rest existed -- trading a LOUD oversize refusal for
# quiet under-review. An id owning NEITHER ledger is still genuinely unresolved.
printf -- '- [ ] [ROUTINE] design-ledger-only item <!-- id:7777 -->\n' >> "$R/TODO.md"
O_to="$TMP/todo_only.md"
err_to="$TMP/err_todo_only.txt"
rc_to=0
"$SLICE" --repo repo --path "$R" --ids 1111,7777 --out "$O_to" >/dev/null 2>"$err_to" || rc_to=$?
[[ "$rc_to" -eq 0 ]] \
  && ok "a TODO-only id does NOT trigger the unresolved exit path (exit 0)" \
  || bad "id:dd59: TODO-only id:7777 exited $rc_to -- it owns a TODO.md entry and is not unresolved"
grep -q '^## TODO-only items' "$O_to" \
  && ok "the slice carries a TODO-only section for an id with no ROADMAP entry" \
  || bad "id:dd59: no 'TODO-only items' section -- a worked design-ledger id was dropped from the slice"
grep -q 'design-ledger-only item' "$O_to" \
  && ok "the TODO-only item's actual text reaches the slice (not just its id)" \
  || bad "id:dd59: TODO-only id:7777 named but its TODO.md line body is missing from the slice"
grep -qF ' 1111' "$O_to" || grep -q 'id:1111' "$O_to" \
  && ok "the ROADMAP-owning id in the same set is still sliced normally" \
  || bad "id:dd59: mixing a TODO-only id into the set broke the normal ROADMAP path"

# An id owning NEITHER ledger must still be NAMED — the TODO-only fallback must not swallow
# it. The exit stays 0 because a slice WAS written for the ids that did resolve (see the
# contract note at case 4); the guarantee is the loud naming, not the exit code.
rc_n=0
"$SLICE" --repo repo --path "$R" --ids 1111,ffff --out "$TMP/neither.md" >/dev/null 2>"$TMP/err_neither.txt" || rc_n=$?
[[ "$rc_n" -eq 0 ]] \
  && ok "a partially-resolvable set still exits 0 (slice written for what resolved)" \
  || bad "id:dd59: partial set exited $rc_n — a good slice would be discarded as MECH-ERROR"
grep -q 'ffff' "$TMP/err_neither.txt" \
  && ok "an id owning NEITHER ROADMAP nor TODO is still NAMED loudly (not swallowed by the TODO fallback)" \
  || bad "id:dd59: the TODO-only fallback swallowed a genuinely unresolvable id -- ffff never named"
[[ -s "$TMP/neither.md" ]] \
  && ok "the partial slice is still written for the id that DID resolve" \
  || bad "id:dd59: no slice written despite one resolvable id"

# ── (5) Malformed token / empty set / duplicate-flag misuse behave predictably. ─────────────
rc3=0; "$SLICE" --repo repo --path "$R" --ids "1111,zzzz" --out "$TMP/bad1.md" >/dev/null 2>"$TMP/err3.txt" || rc3=$?
[[ "$rc3" -eq 2 ]] && ok "a malformed (non-hex) token in --ids exits with the usage code (2)" || bad "id:dd59: malformed token exited $rc3, expected 2"

rc4=0; "$SLICE" --repo repo --path "$R" --ids "" --out "$TMP/bad2.md" >/dev/null 2>"$TMP/err4.txt" || rc4=$?
[[ "$rc4" -eq 2 ]] && ok "an empty --ids value exits with the usage code (2)" || bad "id:dd59: empty --ids exited $rc4, expected 2"

rc5=0; "$SLICE" --repo repo --path "$R" --id 1111 --ids 3333 --out "$TMP/bad3.md" >/dev/null 2>"$TMP/err5.txt" || rc5=$?
[[ "$rc5" -eq 2 ]] && ok "passing both --id and --ids exits with the usage code (2)" || bad "id:dd59: --id + --ids together exited $rc5, expected 2"

# ── (6) Stable ordering across repeated runs (same input -> byte-identical output). ─────────
O_a="$TMP/ord_a.md"; O_b="$TMP/ord_b.md"
"$SLICE" --repo repo --path "$R" --ids 3333,1111 --out "$O_a" >/dev/null
"$SLICE" --repo repo --path "$R" --ids 3333,1111 --out "$O_b" >/dev/null
if diff "$O_a" "$O_b" >/dev/null; then
  ok "identical --ids input produces byte-identical output across repeated runs"
else
  bad "id:dd59: two runs of the same --ids set produced different output"
fi

echo "---"
echo "summary: $pass ok, $fail bad"
[[ "$fail" -eq 0 ]] || exit 1
echo "ALL PASS: ledger-slice.sh slices a set of ids (id:dd59), --id path unchanged"
