#!/usr/bin/env python3
"""meeting-backlinks.py -- regenerate the DERIVED meeting-backlink index.

TODO id:e8af. Answers one question: "which meetings already discussed this id?"
That is the "haven't we settled this before" failure -- a decision gets re-argued
because nothing cheaply maps an `id:XXXX` token back to the notes that already
weighed it.

DOCTRINE (id:2840): markdown is the SSOT, this index is a CACHE. So the index is
its OWN derived file (`docs/ledger-notes/BACKLINKS.md` by default), never an
embedded section inside a hand-edited document, and it is regenerable from the
notes alone. It carries a generated-by marker; a target file WITHOUT that marker
is refused rather than overwritten, so hand-edited content can never be clobbered.

What counts as a citation: `id:XXXX` where XXXX is 4 lowercase hex digits, in any
context -- the `<!-- id:XXXX -->` ledger form AND a bare prose mention alike. A
passing prose mention IS a prior discussion, which is the whole point of the
index. Tokens whose `id:` is part of a longer word (`invalid:aa33`) or a different
marker (`roadmap:aa44`, `routed:aa55`) are not citations.

Modelled on tools/memory-index.py (this repo's reference generated-index tool):
same CLI shape, same atomic write, same "--check exits non-zero on drift".

CLI:
  meeting-backlinks.py [--notes-dir DIR] [--index PATH] [--write | --check]
                       [--min-notes N]

  --check   (default) regenerate in memory, unified-diff against the on-disk
            index, exit 1 if they differ (print the diff), 0 if identical.
  --write   write the index atomically (tmp + rename).
  --min-notes  only list ids cited in at least N notes (default 1).

Exit codes: 0 ok / in-sync; 1 --check drift; 2 LOUD failure (bad path, or a
target file that is not ours to write).

This tool NEVER creates, deletes, or modifies a meeting note -- only the index.
"""
import argparse
import difflib
import os
import re
import sys

DEFAULT_NOTES_DIR = "docs/meeting-notes"
DEFAULT_INDEX = "docs/ledger-notes/BACKLINKS.md"

MARKER = "GENERATED by tools/meeting-backlinks.py"

GEN_NOTE = (MARKER + " -- do not hand-edit. Regenerate with\n"
            "> `tools/meeting-backlinks.py --write`; `--check` exits non-zero on drift.")

# `id:` must not be the tail of a longer word (invalid:, routed:, roadmap: ...),
# and the 4 hex digits must not run on into a longer token.
ID_RE = re.compile(r"(?<![0-9A-Za-z_:-])id:([0-9a-f]{4})(?![0-9A-Za-z_])")


def header(n_ids, n_notes):
    return (
        "# Meeting backlinks -- which meetings already discussed this id\n"
        "\n"
        "> DERIVED index over `docs/meeting-notes/`. Markdown stays the SSOT; this file is a\n"
        "> cache (id:2840). Look an `id:XXXX` up here BEFORE re-opening a question: a token\n"
        "> listed against two or more notes has been argued before.\n"
        "> {note}\n"
        "\n"
        "{ids} ids cited across {notes} notes.\n"
        "\n"
    ).format(note=GEN_NOTE, ids=n_ids, notes=n_notes)


def scan(notes_dir):
    """Return (backlinks, n_notes).

    backlinks maps an id token to a sorted list of note basenames citing it.
    Only regular `*.md` files directly in notes_dir are scanned."""
    files = sorted(
        f for f in os.listdir(notes_dir)
        if f.endswith(".md") and os.path.isfile(os.path.join(notes_dir, f))
    )
    backlinks = {}
    for fn in files:
        with open(os.path.join(notes_dir, fn), encoding="utf-8", errors="replace") as f:
            text = f.read()
        for tok in set(ID_RE.findall(text)):
            backlinks.setdefault(tok, []).append(fn)
    for tok in backlinks:
        backlinks[tok].sort()
    return backlinks, len(files)


def render(backlinks, n_notes, notes_dir, index_path, min_notes):
    """Build the full index text. Deterministic: ids sorted, notes sorted."""
    index_dir = os.path.dirname(os.path.abspath(index_path)) or "."
    rel_dir = os.path.relpath(os.path.abspath(notes_dir), index_dir).replace(os.sep, "/")

    listed = sorted(tok for tok, notes in backlinks.items() if len(notes) >= min_notes)
    out = [header(len(listed), n_notes)]
    for tok in listed:
        notes = backlinks[tok]
        links = ", ".join(
            "[{stem}]({d}/{fn})".format(stem=os.path.splitext(fn)[0], d=rel_dir, fn=fn)
            for fn in notes
        )
        out.append("- **id:{tok}** ({n}) -- {links}\n".format(
            tok=tok, n=len(notes), links=links))
    return "".join(out)


def read_file(path):
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            return f.read()
    return ""


def atomic_write(path, text):
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    tmp = path + ".tmp.%d" % os.getpid()
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, path)


def guard_target(path):
    """Refuse to touch a target that exists without our generated-by marker.

    The index owns its whole file, so anything else living at that path is
    hand-edited content. Returns an error string, or None when it is safe."""
    if not os.path.exists(path):
        return None
    if not os.path.isfile(path):
        return "index path exists and is not a regular file: %s" % path
    if MARKER not in read_file(path):
        return ("refusing to touch %s: it exists but carries no `%s` marker, so it is "
                "hand-edited content. Move it aside or point --index elsewhere."
                % (path, MARKER))
    return None


def default_root():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(here)


def main(argv=None):
    root = default_root()
    ap = argparse.ArgumentParser(
        description="Regenerate the derived meeting-backlink index (id:e8af).")
    ap.add_argument("--notes-dir", default=os.path.join(root, DEFAULT_NOTES_DIR),
                    help="directory of meeting notes (default: %s)" % DEFAULT_NOTES_DIR)
    ap.add_argument("--index", default=os.path.join(root, DEFAULT_INDEX),
                    help="index file to generate (default: %s)" % DEFAULT_INDEX)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the index atomically")
    mode.add_argument("--check", action="store_true",
                      help="(default) diff against on-disk, exit 1 on drift")
    ap.add_argument("--min-notes", type=int, default=1,
                    help="only list ids cited in at least N notes (default 1)")
    args = ap.parse_args(argv)

    if not os.path.isdir(args.notes_dir):
        sys.stderr.write("error: --notes-dir is not a directory: %s\n" % args.notes_dir)
        return 2

    err = guard_target(args.index)
    if err:
        sys.stderr.write("ERROR: %s\n" % err)
        return 2

    backlinks, n_notes = scan(args.notes_dir)
    new = render(backlinks, n_notes, args.notes_dir, args.index, args.min_notes)

    if args.write:
        atomic_write(args.index, new)
        return 0

    old = read_file(args.index)
    if old == new:
        return 0
    diff = difflib.unified_diff(
        old.splitlines(keepends=True), new.splitlines(keepends=True),
        fromfile="%s (on disk)" % args.index, tofile="(generated)")
    sys.stdout.writelines(diff)
    return 1


if __name__ == "__main__":
    sys.exit(main())
