#!/usr/bin/env python3
"""memory-index.py — regenerate a project's MEMORY.md / MEMORY.archive.md index
from the per-memory `*.md` files in a memory directory.

This implements TODO id:2e6d's "derived index" dissolution: the index is
GENERATED from the memory files, so a memory file with no index pointer is
unrepresentable — a dropped pointer cannot survive regeneration.

Stdlib only (Python 3). The YAML frontmatter is hand-parsed (no PyYAML): it
supports top-level `key: value` and 2-space-indented keys under a `metadata:`
block, strips surrounding single/double quotes, joins quoted values that span
lines (so a genuine multi-line hook is detectable), and ignores unknown keys.

CLI:
  memory-index.py --dir DIR [--write | --check] [--ceiling N] [--project NAME]

  --check   (default) regenerate in memory, unified-diff against the on-disk
            index files, exit 1 if they differ (print the diff), 0 if identical.
  --write   write both index files atomically (tmp + rename).
  --ceiling byte ceiling for MEMORY.md only (default 17100); over → stderr WARNING
            (never a failure).
  --project name used in the header; default = basename of the memory dir's
            parent-parent, else "project".

Exit codes: 0 ok / in-sync; 1 --check drift; 2 LOUD validation failure.
This tool NEVER creates, deletes, or modifies any memory `*.md` file — only the
two index files.
"""
import argparse
import difflib
import math
import os
import re
import subprocess
import sys

INDEX_FILE = "MEMORY.md"
ARCHIVE_FILE = "MEMORY.archive.md"

# em-dash U+2014 surrounded by single spaces
DASH = " — "

GEN_NOTE = ("GENERATED by tools/memory-index.py — do not hand-edit; add a `hook:` to a "
            "memory file's frontmatter, and set `metadata.archived: true` to archive it.")


def header_active(project):
    return (
        "# Project memory — {p}\n"
        "\n"
        "> Index = one terse hook per memory. Full detail (child ids, mechanism, rationale)\n"
        "> lives in each topic file — open before acting. {note}\n"
        "\n"
    ).format(p=project, note=GEN_NOTE)


def header_archive(project):
    return (
        "# Memory archive — {p}\n"
        "\n"
        "> Settled/historical memories: decision closed, incident resolved, or design shipped.\n"
        "> The memory FILES are untouched and all `[[wiki-links]]` still resolve — only the index\n"
        "> pointer moved here, out of the per-session recall path. GENERATED by tools/memory-index.py\n"
        "> — do not hand-edit; set `metadata.archived: true` in the memory file instead.\n"
        "\n"
    ).format(p=project)


# ── frontmatter parsing ──────────────────────────────────────────────────────

def _find_close(s, q):
    """Index of the first unescaped quote char q in s, or None."""
    k = 0
    while k < len(s):
        if s[k] == "\\":
            k += 2
            continue
        if s[k] == q:
            return k
        k += 1
    return None


def _unescape(s):
    return s.replace('\\"', '"').replace("\\'", "'").replace("\\\\", "\\")


def _read_value(val, lines, i):
    """Return (value, last_index_consumed).

    If val opens with a quote that does not close on the same line, accumulate
    following lines (joined with '\n') until the closing quote — so a value that
    genuinely spans lines carries a real newline and is detectable downstream.
    Stops at a lone '---' (frontmatter terminator) to avoid over-reading.
    """
    if val and val[0] in ('"', "'"):
        q = val[0]
        rest = val[1:]
        idx = _find_close(rest, q)
        if idx is not None:
            return _unescape(rest[:idx]), i
        parts = [rest]
        j = i + 1
        while j < len(lines):
            line = lines[j]
            if line.strip() == "---":
                break
            idx = _find_close(line, q)
            if idx is not None:
                parts.append(line[:idx])
                return _unescape("\n".join(parts)), j
            parts.append(line)
            j += 1
        # unterminated quote: return what we have (still may contain a newline)
        return _unescape("\n".join(parts)), min(j, len(lines) - 1)
    return val, i


def parse_frontmatter(path):
    """Return a dict of frontmatter keys parsed from a file on disk."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    return parse_frontmatter_text(text)


def parse_frontmatter_text(text):
    """Return a dict of frontmatter keys. Nested metadata keys are stored as
    'metadata.<key>'. Returns {} if the text has no leading '---' block."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    fm = {}
    in_metadata = False
    i = 1
    n = len(lines)
    while i < n:
        line = lines[i]
        if line.strip() == "---":
            break
        if line.strip() == "":
            i += 1
            continue
        indent = len(line) - len(line.lstrip(" "))
        content = line.strip()
        if ":" not in content:
            i += 1
            continue
        key, _, rawval = content.partition(":")
        key = key.strip()
        val = rawval.strip()
        if indent == 0:
            if key == "metadata" and val == "":
                in_metadata = True
                i += 1
                continue
            in_metadata = False
            target = key
        else:
            if not in_metadata:
                i += 1
                continue
            target = "metadata." + key
        val, i = _read_value(val, lines, i)
        fm[target] = val
        i += 1
    return fm


# ── model ────────────────────────────────────────────────────────────────────

class Entry:
    __slots__ = ("filename", "name", "hook", "archived")

    def __init__(self, filename, name, hook, archived):
        self.filename = filename
        self.name = name
        self.hook = hook
        self.archived = archived

    def line(self):
        return "- [{n}]({f}){d}{h}".format(n=self.name, f=self.filename, d=DASH, h=self.hook)


def link_targets(text):
    """Ordered, de-duplicated list of `](target)` link targets in an index file."""
    seen = set()
    out = []
    for m in re.finditer(r"\]\(([^)]+)\)", text):
        t = m.group(1)
        if t not in seen:
            seen.add(t)
            out.append(t)
    return out


def build_entries(memory_dir, errors):
    """Return an ordered list of Entry objects. Order = pointer order from the
    existing index files (ordering cache), then any pointerless files sorted by
    filename. Validation problems are appended to `errors` (LOUD, exit 2)."""
    files = sorted(
        f for f in os.listdir(memory_dir)
        if f.endswith(".md") and f not in (INDEX_FILE, ARCHIVE_FILE)
        and os.path.isfile(os.path.join(memory_dir, f))
    )
    fileset = set(files)

    # ordering cache: existing pointer order across both index files
    cache = []
    seen = set()
    for idx in (INDEX_FILE, ARCHIVE_FILE):
        p = os.path.join(memory_dir, idx)
        if os.path.isfile(p):
            with open(p, encoding="utf-8") as f:
                for t in link_targets(f.read()):
                    if t not in seen:
                        seen.add(t)
                        cache.append(t)

    ordered = []
    used = set()
    for t in cache:
        if t in fileset and t not in used:
            ordered.append(t)
            used.add(t)
    # pointerless files appended, sorted by filename (they were sorted above)
    for f in files:
        if f not in used:
            ordered.append(f)
            used.add(f)

    entries = []
    for fn in ordered:
        fm = parse_frontmatter(os.path.join(memory_dir, fn))
        # Display title, most-specific first: title: → metadata.title → name: →
        # metadata.name → filename stem. A writer sometimes re-nests title:/hook:
        # under a `metadata:` block (observed twice 2026-07-17, id:e875) — resolve
        # from there too rather than silently falling back to the stem/description.
        # The stem only FILLS a missing field, never overrides an explicit one
        # (some names legitimately contain spaces).
        name = (fm.get("title") or fm.get("metadata.title")
                or fm.get("name") or fm.get("metadata.name")
                or os.path.splitext(fn)[0])
        hook = fm.get("hook")
        if hook is None and fm.get("metadata.hook") is not None:
            hook = fm.get("metadata.hook")
            print("WARNING: %s: `hook:` found only under `metadata:` — "
                  "resolved from metadata.hook (fix: move it to top level)" % fn,
                  file=sys.stderr)
        desc = fm.get("description") or fm.get("metadata.description")
        if hook is None:
            hook = desc
        if hook is None:
            errors.append("%s: memory file has neither `hook:` nor `description:`" % fn)
            continue
        if "\n" in hook:
            errors.append("%s: hook/description contains a newline (must be a single line)" % fn)
            continue
        archived = str(fm.get("metadata.archived", "")).strip().lower() == "true"
        if archived and fn.startswith("feedback-"):
            errors.append("%s: durable user preference (feedback-*) must never be archived "
                          "(metadata.archived: true)" % fn)
            continue
        entries.append(Entry(fn, name, hook, archived))
    return entries


def render(entries, project):
    active = [e for e in entries if not e.archived]
    archived = [e for e in entries if e.archived]

    body = header_active(project)
    body += "\n".join(e.line() for e in active)
    body += "\n"

    arch = header_archive(project)
    arch += "\n".join(e.line() for e in archived)
    arch += "\n"
    return body, arch


# ── hook-text invariants (diff vs git HEAD, id:7d97) ─────────────────────────
#
# tools/memory-index.py --check proves only that the index is *derivable* from
# the memory files; it says nothing about whether a hook's TEXT still means what
# it did before. A bulk rewrite can preserve every id:/routed: token, wiki-link,
# and entry count while silently stripping meaning (2026-07-10: an Opus
# compaction agent stripped the `user:` prefix from 14/15 feedback-* hooks and
# flattened emphasis in 62 more, while every mechanical invariant above still
# held). This section diffs each entry's hook against the previous COMMITTED
# state (`git show HEAD:<path>`) and flags two specific regressions. It is a
# diff-vs-HEAD check, not a style rule, and is deliberately narrow: semantic
# drift with every token intact is out of scope (an LLM-review residual).

_EMPHASIS_RE = re.compile(r"\*\*[^*]+\*\*")
_ALLCAPS_RE = re.compile(r"\b[A-Z]{2,}\b")


def emphasis_tokens(text):
    """Set of emphasis markers in a hook string: **bold** spans and ALL-CAPS
    words. Used to detect a token present before and absent after."""
    if not text:
        return set()
    return set(_EMPHASIS_RE.findall(text)) | set(_ALLCAPS_RE.findall(text))


def git_head_text(memory_dir, filename):
    """Return the git-HEAD content of memory_dir/filename as a string, or None
    if it can't be determined (not a git repo, git missing, file has no HEAD
    version — i.e. a brand-new memory — or any other git failure). Fail-open:
    every failure mode here just means "no previous state to compare", never
    a crash."""
    path = os.path.join(memory_dir, filename)
    try:
        top = subprocess.run(
            ["git", "-C", memory_dir, "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, timeout=10)
        if top.returncode != 0:
            return None
        root = top.stdout.strip()
        relpath = os.path.relpath(os.path.abspath(path), root).replace(os.sep, "/")
        shown = subprocess.run(
            ["git", "-C", root, "show", "HEAD:%s" % relpath],
            capture_output=True, text=True, timeout=10)
        if shown.returncode != 0:
            return None
        return shown.stdout
    except (OSError, subprocess.SubprocessError):
        return None


def hook_from_frontmatter_text(text):
    """Same hook/description fallback build_entries() uses, applied to raw
    frontmatter text (e.g. a git-HEAD blob) instead of an on-disk file."""
    fm = parse_frontmatter_text(text)
    hook = fm.get("hook") or fm.get("metadata.hook")
    if hook is None:
        hook = fm.get("description") or fm.get("metadata.description")
    return hook


def check_hook_invariants(memory_dir, entries):
    """Return a list of human-readable violation strings: entries whose hook
    text regressed against the last COMMITTED state. Two invariants:
      (a) hook began 'user:' in HEAD, no longer does — a directive read as a
          plain observation.
      (b) hook loses a **bold**/ALL-CAPS emphasis token present in HEAD.
    A brand-new memory (no HEAD version) is never flagged (fail-open)."""
    violations = []
    for e in entries:
        old_text = git_head_text(memory_dir, e.filename)
        if old_text is None:
            continue
        old_hook = hook_from_frontmatter_text(old_text)
        if old_hook is None:
            continue
        new_hook = e.hook
        if old_hook.strip().startswith("user:") and not new_hook.strip().startswith("user:"):
            violations.append(
                "%s: hook lost the 'user:' prefix (was: %r, now: %r)"
                % (e.filename, old_hook, new_hook))
        lost = emphasis_tokens(old_hook) - emphasis_tokens(new_hook)
        if lost:
            violations.append(
                "%s: hook lost emphasis token(s) %s (was: %r, now: %r)"
                % (e.filename, sorted(lost), old_hook, new_hook))
    return violations


# ── I/O ──────────────────────────────────────────────────────────────────────

def read_file(path):
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            return f.read()
    return ""


def atomic_write(path, text):
    tmp = path + ".tmp.%d" % os.getpid()
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, path)


def size_warning(body, ceiling, entries):
    n = len(body.encode("utf-8"))
    if n <= ceiling:
        return
    over = n - ceiling
    active = [e for e in entries if not e.archived]
    line_bytes = sum(len((e.line() + "\n").encode("utf-8")) for e in active)
    mean = (line_bytes / len(active)) if active else 1.0
    need = math.ceil(over / mean) if mean > 0 else 0
    sys.stderr.write(
        "WARNING: MEMORY.md is %d bytes (%d over the %d ceiling); archive ~%d "
        "entr%s to fit.\n" % (n, over, ceiling, need, "y" if need == 1 else "ies"))


def default_project(memory_dir):
    ap = os.path.abspath(memory_dir)
    pp = os.path.dirname(os.path.dirname(ap))
    base = os.path.basename(pp)
    return base or "project"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Regenerate MEMORY.md / MEMORY.archive.md.")
    ap.add_argument("--dir", required=True, help="memory directory")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write both index files atomically")
    mode.add_argument("--check", action="store_true",
                      help="(default) diff against on-disk, exit 1 on drift")
    ap.add_argument("--ceiling", type=int, default=17100, help="byte ceiling for MEMORY.md")
    ap.add_argument("--project", default=None, help="header project name")
    args = ap.parse_args(argv)

    memory_dir = args.dir
    if not os.path.isdir(memory_dir):
        sys.stderr.write("error: --dir is not a directory: %s\n" % memory_dir)
        return 2

    project = args.project or default_project(memory_dir)

    errors = []
    entries = build_entries(memory_dir, errors)
    if errors:
        for e in errors:
            sys.stderr.write("ERROR: %s\n" % e)
        return 2

    body, arch = render(entries, project)
    size_warning(body, args.ceiling, entries)

    body_path = os.path.join(memory_dir, INDEX_FILE)
    arch_path = os.path.join(memory_dir, ARCHIVE_FILE)

    if args.write:
        atomic_write(body_path, body)
        atomic_write(arch_path, arch)
        return 0

    # default: --check
    drift = False
    for path, new, label in ((body_path, body, INDEX_FILE), (arch_path, arch, ARCHIVE_FILE)):
        old = read_file(path)
        if old != new:
            drift = True
            diff = difflib.unified_diff(
                old.splitlines(keepends=True), new.splitlines(keepends=True),
                fromfile="%s (on disk)" % label, tofile="%s (generated)" % label)
            sys.stdout.writelines(diff)

    for violation in check_hook_invariants(memory_dir, entries):
        drift = True
        sys.stdout.write("ERROR: %s\n" % violation)

    return 1 if drift else 0


if __name__ == "__main__":
    sys.exit(main())
